
### lambda health

GET https://ds-api.staging.sandbox.tubi.io/api/health
X-Message: hello world!

### signin

# User should use existing anonymous token to signin. Here just for demo purpose.

# @name login
POST http://ds-api.staging.sandbox.tubi.io/api/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "abcd1234"
}

### list datasets

# retrieve token as echo service need it.

@token = {{ login.response.body.token }}

GET http://ds-api.staging.sandbox.tubi.io/api/datasets
Authorization: Bearer {{ token }}

### get dataset

GET http://ds-api.staging.sandbox.tubi.io/api/datasets/youtube.parquet
Authorization: Bearer {{ token }}
