
### lambda health

GET httpss://ds-api.staging.sandbox.tubi.io/api/health
X-Message: hello world!

### signin

# User should use existing anonymous token to signin. Here just for demo purpose.

# @name login
POST https://ds-api.staging.sandbox.tubi.io/api/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "abcd1234"
}

### list datasets

# retrieve token as echo service need it.

@token = {{ login.response.body.token }}

GET https://ds-api.staging.sandbox.tubi.io/api/datasets
Authorization: Bearer {{ token }}

### get dataset

GET https://ds-api.staging.sandbox.tubi.io/api/datasets/youtube.parquet
Authorization: Bearer {{ token }}

### query dataset

POST https://ds-api.staging.sandbox.tubi.io/api/datasets/flights.parquet/query
Authorization: Bearer {{ token }}

{
  "sql": "select * from flights limit 10"
}
