# Minerva REST API

### signin

# User should use existing anonymous token to signin. Here just for demo purpose.

# @name login
POST http://localhost:3000/api/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "abcd1234"
}

### echo

# retrieve token as echo service need it.

@token = {{ login.response.body.token }}

GET http://localhost:3000/api/health
X-Message: hello world!

### list datasets

GET http://localhost:3000/api/datasets
Authorization: Bearer {{ token }}

### show one dataset

GET http://localhost:3000/api/datasets/players.parquet
Authorization: Bearer {{ token }}

### query dataset

POST http://localhost:3000/api/datasets/players_new.parquet*/query
Authorization: Bearer {{ token }}

{
  "sql": "select * from players_new limit 10"
}
